defaults: &defaults
  tutorial_url: "http://www.railstutorial.org/help"
  book_url: "http://www.railstutorial.org/book"
  main_url: "http://www.railstutorial.org/"

user:
  name:
    max_length: 50
  email:
    max_length: 255
    email_regex: \A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z
    case_sensitive: false
  password:
    min_length: 8
  avatar_url: https://secure.gravatar.com/avatar
  create_successfull: "User created successfull"
    
development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults
