defaults: &defaults
  tutorial_url: "http://www.railstutorial.org/help"
  book_url: "http://www.railstutorial.org/book"
  main_url: "http://www.railstutorial.org/"
  time_expired: 2
  digit_140: 140
  digit_50: 50 
  image_types: ["image/jpeg", "image/png", "image/gif"]
  max_image_size: 5
  micropost_image_height: 400
  micropost_image_width: 400
  relationship_name: "Relationship"
  user_class: "User"
user:
  name:
    max_length: 50
  email:
    max_length: 255
    email_regex: \A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z
    case_sensitive: false
  password:
    min_length: 8
  avatar_url: https://secure.gravatar.com/avatar
  create_successfull: "User created successfull"
  gravatar_email: "http://gravatar.com/emails"
  pagy_items: 10
  gravatar_size : 80
  gravatar_size_small : 30
  gravatar_size_user: 50
development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults
